### ISSUE TITLE
Your Command Line Tools are too outdated

### ISSUE THREAD

**Issue by toddjonker** [amazon-ion/homebrew-ion-cli#2]
When running `brew install ion-cli` I get this error:
```
[~]$ brew install ion-cli
==> Downloading https://ghcr.io/v2/homebrew/core/libssh2/manifests/1.10.0
.
.
.
==> Installing ion-cli from amazon-ion/ion-cli
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.4.
```
According to Software Update, the only thing that's outdated is the OS itself: I've got macOS 12.5 but 12.5.1 has just come out and I haven't installed it.  That's surprisingly tight to be "too outdated", and I suspect it's not the real issue.

(I don't know whether you have any control over the error message, but more details therein would certainly be appreciated.)

I'll try again after updating my OS, and will update this issue with the results. Wanted to capture this output before doing so.

**Comment by popematt** [comment]
I would be surprised if the problem is that your OS is outdated. I am currently running macOS 12.4, and I was able to install it without any issue.

From what I can tell, Command Line Tools doesn't get updated through the normal macOS channels, so it may be out of date even Software Update says that there are no updates available. You can check the version of Command Line Tools by running:
```
pkgutil --pkg-info=com.apple.pkg.CLTools_Executables | grep version
```

If the output indicates a version less than 13.4, then I think Homebrew's suggestion of running `xcode-select` is probably your best bet:

```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```

**Comment by toddjonker** [comment]
After updating to macOS 12.5.1, re-running `brew install ion-cli` gives the same error.

I'm hesitant to run `sudo xcode-select --install` as suggested by Homebrew, since I don't want to install all of Xcode, just the Command Line Tools.

Following your suggestion:
```
[~]$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables | grep version
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
```

**Comment by toddjonker** [comment]
> From what I can tell, Command Line Tools doesn't get updated through the normal macOS channels

xcode-select seems to suggest otherwise:
```
[~]$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

That said, this is a managed laptop with controls around such updates; maybe the CLI tools are being filtered at that level...

**Comment by toddjonker** [comment]
```
[~]$ brew config
HOMEBREW_VERSION: 3.5.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: c5731faf8be1ddc1eeae4b162b88bd76318fc279
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ebec0967d6d28aefe31e15f93310323fc9bed167
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacs
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.37.2 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5.1-arm64
CLT: 12.5.0.22.9
Xcode: N/A
Rosetta 2: false
```

**Comment by toddjonker** [comment]
Worked-around by doing a fresh install of the CLI tools:
```
[~]$ sudo mv /Library/Developer/CommandLineTools /Library/Developer/CommandLineTools-bak
Password:
[~]$ sudo xcode-select --install
xcode-select: note: install requested for command line developer tools
[~]$ brew install ion-cli
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
.
.
.
==> Running `brew cleanup ion-cli`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
[~]$ which ion
/opt/homebrew/bin/ion
[~]$ ion -V
ion 0.4.1
```
I'll close this issue since it seems that the failure-to-update problem is macOS's (though not handled particularly clearly by Homebrew) and out of control of the Ion CLI installer.

Thanks!

**Comment by popematt** [comment]
For anyone else who comes across this is future, the clues that indicated a problem with the Command Line Tools installation were (1) that `pkgutil` and `xcode-select` disagreed as to whether Command Line Tools was present, and (2) that `brew config` and `clang --version` both indicated out-of-date Command Line Tools, but `softwareupdate` said that there were no updates available.
